/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/java_library_plugin.html
 */

plugins {
    //id("project-report")
}

allprojects {
    group = "uk.co.magictractor"
    version = "0.0.1-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

subprojects {

    apply(plugin="java-library")
    apply(plugin="checkstyle")

    dependencies {
        // The reason for quotes around "api" and "testImplementation" is explained
        // in https://github.com/gradle/kotlin-dsl/issues/843
        "api"("org.slf4j:slf4j-api:1.7.26")
        //"testImplementation"("org.slf4j:slf4j-api:1.7.26")
        "testImplementation"("ch.qos.logback:logback-classic:1.2.3")
        "testImplementation"("org.junit.jupiter:junit-jupiter-api:5.4.2")
        "testImplementation"("org.junit.jupiter:junit-jupiter-engine:5.4.2")
        "testImplementation"("org.assertj:assertj-core:3.11.1")
    }

    // See https://docs.gradle.org/current/userguide/build_environment.html
    //tasks.withType<JavaCompile>().configureEach {
    tasks.withType<JavaCompile> {
        options.compilerArgs = listOf("-Xdoclint:none", "-Xlint:none", "-nowarn")
    }

    tasks.withType<Test> {
        useJUnitPlatform() {
            filter {
                excludeTags("within-suite")
            }
        }
    }

}
