/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/java_library_plugin.html
 */

//import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

// TODO! add a bom? https://docs.gradle.org/5.2/userguide/java_platform_plugin.html

plugins {
    //id("java-library") // apply false
    //id("project-report")
}

allprojects {
    group = "uk.co.magictractor"
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

//val testImplementation by configurations

//configure(subprojects) {
subprojects {
    version = "0.0.1"

    apply(plugin="java-library")
    apply(plugin="checkstyle")

    //afterEvaluate {
    dependencies {
        // This dependency is exported to consumers, that is to say found on their compile classpath.
        //api("org.apache.commons:commons-math3:3.6.1")

        // This dependency is used internally, and not exposed to consumers on their own compile classpath.
        //implementation("com.google.guava:guava:27.0.1-jre")

        // Use JUnit test framework
        //testImplementation("junit:junit:4.12")
    
        //testImplementation("org.slf4j:slf4j-api:1.7.26")
        "api"("org.slf4j:slf4j-api:1.7.26")
        //"testImplementation"("org.slf4j:slf4j-api:1.7.26")
        "testImplementation"("ch.qos.logback:logback-classic:1.2.3")
        "testImplementation"("org.junit.jupiter:junit-jupiter-api:5.4.2")
        "testImplementation"("org.junit.jupiter:junit-jupiter-engine:5.4.2")
        "testImplementation"("org.assertj:assertj-core:3.11.1")
    }
    //}

    tasks.withType<Test> {
        useJUnitPlatform()
    }

}

